In [43]:
import numpy as np
import pandas as pd

In [44]:
df=pd.read_csv('/kaggle/input/csvtrain/train_complaints.csv')

In [45]:
df.head()

,complaint_id,complaint_text,primary_category,secondary_category,severity
0,1634299,Back into XXXX of 2010 during this mortgage cr...,Mortgage,"Loan modification,collection,foreclosure",2
1,5505088,I checked my credit report and I am upset on w...,"Credit reporting, credit repair services, or o...",Problem with a credit reporting company's inve...,1
2,10979675,I am writing to dispute the accuracy of the in...,Credit reporting or other personal consumer re...,Problem with a company's investigation into an...,1
3,7520351,A transaction from XXXX XXXX XXXX submitted a ...,Checking or savings account,Managing an account,1
4,5847870,I was recently alerted to an account in collec...,Debt collection,Attempts to collect debt not owed,5

In [46]:
df['primary_category'].value_counts()

primary_category
Credit reporting or other personal consumer reports                             735
Mortgage                                                                        611
Debt collection                                                                 579
Credit reporting, credit repair services, or other personal consumer reports    463
Credit reporting                                                                308
Checking or savings account                                                     292
Credit card                                                                       5
Vehicle loan or lease                                                             3
Credit card or prepaid card                                                       3
Name: count, dtype: int64

In [47]:
df['secondary_category'].value_counts()

secondary_category
Problem with a company's investigation into an existing problem                     311
Problem with a credit reporting company's investigation into an existing problem    310
Trouble during payment process                                                      309
Incorrect information on credit report                                              308
Loan modification,collection,foreclosure                                            301
Incorrect information on your report                                                298
Attempts to collect debt not owed                                                   295
Managing an account                                                                 292
Improper use of your report                                                         291
Written notification about debt                                                     284
Name: count, dtype: int64

## Data preprocessing

In [48]:
import re
def remove_tags(text):
  clean_text=re.sub(re.compile('<.$%&*()>{}?/#@!~''",+-'), '', text)
  return clean_text

In [49]:
df['complaint_text']=df['complaint_text'].apply(remove_tags)

In [50]:
df['complaint_text']=df['complaint_text'].apply(lambda x:x.lower())

In [51]:
df

,complaint_id,complaint_text,primary_category,secondary_category,severity
0,1634299,back into xxxx of 2010 during this mortgage cr...,Mortgage,"Loan modification,collection,foreclosure",2
1,5505088,i checked my credit report and i am upset on w...,"Credit reporting, credit repair services, or o...",Problem with a credit reporting company's inve...,1
2,10979675,i am writing to dispute the accuracy of the in...,Credit reporting or other personal consumer re...,Problem with a company's investigation into an...,1
3,7520351,a transaction from xxxx xxxx xxxx submitted a ...,Checking or savings account,Managing an account,1
4,5847870,i was recently alerted to an account in collec...,Debt collection,Attempts to collect debt not owed,5
...,...,...,...,...,...
2994,13965958,the servicing of my mortgage account was trans...,Mortgage,Trouble during payment process,1
2995,9622950,i am writing to delete the following informati...,Credit reporting or other personal consumer re...,Incorrect information on your report,5
2996,14268251,equifax information services xxxx xxxx xxxx xx...,Credit reporting or other personal consumer re...,Incorrect information on your report,5
2997,13284349,i have not supplied proof under the doctrine o...,Credit reporting or other personal consumer re...,Incorrect information on your report,1
2998,14696195,i am writing to formally document that the deb...,Debt collection,Written notification about debt,3

In [52]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sw_list=stopwords.words('english')
df['complaint_text']=df['complaint_text'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [53]:
df

,complaint_id,complaint_text,primary_category,secondary_category,severity
0,1634299,back xxxx 2010 mortgage crash wife part second...,Mortgage,"Loan modification,collection,foreclosure",2
1,5505088,checked credit report upset found out. late pa...,"Credit reporting, credit repair services, or o...",Problem with a credit reporting company's inve...,1
2,10979675,writing dispute accuracy information regarding...,Credit reporting or other personal consumer re...,Problem with a company's investigation into an...,1
3,7520351,transaction xxxx xxxx xxxx submitted withdrawa...,Checking or savings account,Managing an account,1
4,5847870,recently alerted account collections sum {$500...,Debt collection,Attempts to collect debt not owed,5
...,...,...,...,...,...
2994,13965958,servicing mortgage account transferred xxxxxxx...,Mortgage,Trouble during payment process,1
2995,9622950,writing delete following information file. ite...,Credit reporting or other personal consumer re...,Incorrect information on your report,5
2996,14268251,equifax information services xxxx xxxx xxxx xx...,Credit reporting or other personal consumer re...,Incorrect information on your report,5
2997,13284349,"supplied proof doctrine estoppel silence, enge...",Credit reporting or other personal consumer re...,Incorrect information on your report,1
2998,14696195,writing formally document debt collector faile...,Debt collection,Written notification about debt,3

In [54]:
X=df['complaint_text']
Y=df['primary_category']
Z=df['secondary_category']

In [55]:
X

0       back xxxx 2010 mortgage crash wife part second...
1       checked credit report upset found out. late pa...
2       writing dispute accuracy information regarding...
3       transaction xxxx xxxx xxxx submitted withdrawa...
4       recently alerted account collections sum {$500...
                              ...
2994    servicing mortgage account transferred xxxxxxx...
2995    writing delete following information file. ite...
2996    equifax information services xxxx xxxx xxxx xx...
2997    supplied proof doctrine estoppel silence, enge...
2998    writing formally document debt collector faile...
Name: complaint_text, Length: 2999, dtype: object

In [56]:
Y

0                                                Mortgage
1       Credit reporting, credit repair services, or o...
2       Credit reporting or other personal consumer re...
3                             Checking or savings account
4                                         Debt collection
                              ...
2994                                             Mortgage
2995    Credit reporting or other personal consumer re...
2996    Credit reporting or other personal consumer re...
2997    Credit reporting or other personal consumer re...
2998                                      Debt collection
Name: primary_category, Length: 2999, dtype: object

In [57]:
Z

0                Loan modification,collection,foreclosure
1       Problem with a credit reporting company's inve...
2       Problem with a company's investigation into an...
3                                     Managing an account
4                       Attempts to collect debt not owed
                              ...
2994                       Trouble during payment process
2995                 Incorrect information on your report
2996                 Incorrect information on your report
2997                 Incorrect information on your report
2998                      Written notification about debt
Name: secondary_category, Length: 2999, dtype: object

In [58]:
from sklearn.preprocessing import LabelEncoder
primary_encoder = LabelEncoder()
secondary_encoder = LabelEncoder()
Y=primary_encoder.fit_transform(Y)

In [59]:
Y

array([7, 5, 4, ..., 4, 4, 6])

In [60]:
Z=secondary_encoder.fit_transform(Z)

In [61]:
Z

array([4, 7, 6, ..., 3, 3, 9])

# Model for Complaint_text and primary_category

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.001,random_state=1)

In [63]:
X_train.shape

(2996,)

In [64]:
from sklearn.feature_extraction.text import CountVectorizer

In [65]:
cv_primary = CountVectorizer(ngram_range=(1,2))
cv_secondary = CountVectorizer(ngram_range=(1,2))
cv_severity = CountVectorizer(ngram_range=(1,2))

In [66]:
X_train_bow = cv_primary.fit_transform(X_train).toarray()
X_test_bow = cv_primary.transform(X_test).toarray()

In [67]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train_bow,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [68]:
Y_pred=lr.predict(X_test_bow)

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test, Y_pred)

0.3333333333333333

# Model for Complaint_Text and Secondary_category

In [69]:
from sklearn.model_selection import train_test_split
X_train2,X_test2,Z_train,Z_test=train_test_split(X,Z,test_size=0.001,random_state=1)

In [70]:
X_train2_bow = cv_secondary.fit_transform(X_train2).toarray()
X_test2_bow = cv_secondary.transform(X_test2).toarray()

In [71]:
from sklearn.linear_model import LogisticRegression
mod=LogisticRegression(random_state=16)
mod.fit(X_train2_bow,Z_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=16)

In [72]:
Z_pred=mod.predict(X_test2_bow)

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Z_test, Z_pred)

0.6666666666666666

# Model for Complaint Text and Severity

In [73]:
from sklearn.preprocessing import LabelEncoder
severity_encoder=LabelEncoder()
S = df['severity']
S = severity_encoder.fit_transform(S)

In [74]:
S

array([1, 0, 0, ..., 4, 0, 2])

In [75]:
from sklearn.model_selection import train_test_split
X_train3,X_test3,S_train,S_test=train_test_split(X,S,test_size=0.001,random_state=1)

In [76]:
X_train3_bow = cv_severity.fit_transform(X_train3).toarray()
X_test3_bow = cv_severity.transform(X_test3).toarray()

In [77]:
from sklearn.linear_model import LogisticRegression
lr1=LogisticRegression()
lr1.fit(X_train3_bow,S_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [78]:
S_pred=lr1.predict(X_test3_bow)

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(S_test, S_pred)

1.0

# Final CSV

In [79]:
test_df = pd.read_csv('/kaggle/input/csvfiles/test_complaints.csv')
test_df['complaint_text'] = test_df['complaint_text'].apply(remove_tags)
test_df['complaint_text'] = test_df['complaint_text'].str.lower()
test_df['complaint_text'] = test_df['complaint_text'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [80]:
X_test_primary = cv_primary.transform(test_df['complaint_text'])
X_test_secondary = cv_secondary.transform(test_df['complaint_text'])
X_test_severity = cv_severity.transform(test_df['complaint_text'])

primary_pred = lr.predict(X_test_primary)
secondary_pred = mod.predict(X_test_secondary)
severity_pred = lr1.predict(X_test_severity)

In [81]:
primary_pred_labels = primary_encoder.inverse_transform(primary_pred)
secondary_pred_labels = secondary_encoder.inverse_transform(secondary_pred)
severity_pred_labels = severity_encoder.inverse_transform(severity_pred)

In [83]:
wdf=pd.read_csv('/kaggle/input/csvfiles/test_complaints.csv')
complaint_id=wdf['complaint_id']
complaint_text=wdf['complaint_text']

final_df = pd.DataFrame({
    'complaint_id': complaint_id,
    'complaint_text': complaint_text,
    'primary_category': primary_pred_labels,
    'secondary_category': secondary_pred_labels,
    'severity': severity_pred_labels
})

final_df.to_csv('/kaggle/working/final_predictions.csv', index=False)